version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vi7700
      POSTGRES_DB: graphql-playground
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            database: graphql-playground
            schema: public
            user: postgres
            password: vi7700
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
